apiVersion: krit.jaceystan.com/v1alpha1
kind: ConsoleTemplate
metadata:
  labels:
    app.kubernetes.io/name: krit
    app.kubernetes.io/managed-by: kustomize
  name: consoletemplate-sample
spec:
  # TODO(user): Add fields here
